image: node:10.0.0
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master
